### ISSUE TITLE
idle: unable to specify more than 1 subsystem

### ISSUE THREAD

**Issue by girst** [Mic92/python-mpd2#107]
MPD allows for more than one subsystem to be idled on. If for example I need to listen for changes on player and mixer, I'd send this command to mpd: `idle player mixer`.

However, python-mpd2 only takes a string as argument to idle, and even quotes it. Issuing `client.idle('player')` shows `idle player` (as expected) on the wire, but `client.idle('player mixer')` gets turned into `idle "player mixer"`. `client.idle(['player', 'mixer'])` is even worse: `idle "['player', 'mixer']"`.

I'd propose to simply not appy quotes to idle(), as only a small number of keywords (all without spaces) are allowed to be sent as arguments to idle.

**Comment by rnixx** [comment]
Currently it's supposed to call idle, as result you get the affected subsystem. What's wrong with this approach?

**Comment by girst** [comment]
I've just written a lengthy 400 word reply and in the end found out you 
can actually do what I want with varargs. looking at the documentation 
for idle(), nothing hints at how more than one subsystem can be 
specified, so that might be a thing to add.

for those wondering:

     client.idle("player", "mixer")

you can file that as PEBCAK; sorry for the noise.
