### ISSUE TITLE
 Importing ABC directly from collections module was removed in Python 3.9

### ISSUE THREAD

**Issue by tirkarthi** [Mic92/python-mpd2#108]
https://bugzilla.redhat.com/show_bug.cgi?id=1792974

https://github.com/Mic92/python-mpd2/blob/6588692e620dbf7847c84fdb23f507a4e2986194/mpd/base.py#L20

Thanks for the library!

**Comment by Mic92** [comment]
1.1.0 now includes this fix as well.
