### ISSUE TITLE
ALSA error when executing MPDClient.play()

### ISSUE THREAD

**Issue by dubaleeiro** [Mic92/python-mpd2#110]
Hello,

I am trying to play a radio station using the MPDClient.play() but I get the following error:

`'Failed to open "My ALSA Device" (alsa); Failed to open ALSA device "plug:dmix": Device or resource busy'`

Would appretiate some help here... thanks!

**Comment by Mic92** [comment]
This looks like a configuration error of MPD itself.
This library only controls aspect such as play & pause or playlists.
This error however is related to mpd audio output configuration.
You might want to remove all ALSA configuration you added i.e. the `plug:dmix` section or try pulseaudio instead: https://wiki.archlinux.org/index.php/Music_Player_Daemon#Audio_configuration

**Comment by dubaleeiro** [comment]
Thanks for the hint I found a solution and post it here:
[https://github.com/google/aiyprojects-raspbian/issues/683]
