### ISSUE TITLE
mpd.py socket.error 

### ISSUE THREAD

**Issue by novski** [Mic92/python-mpd2#116]
https://github.com/mrstegeman/mpd-webthing/issues/2#issue-619776032
Is this related to python-mpd2 or do I have to report that somewhere else?
Can you make it > v3.4 suitable?

**Comment by Mic92** [comment]
If you upgrade to 1.1 it should be compatible up to python3.8: https://github.com/Mic92/python-mpd2/blob/master/doc/changes.rst#changes-in-v110

These are the versions that we are testing on: https://travis-ci.org/github/Mic92/python-mpd2/builds/687496110

**Comment by Mic92** [comment]
Your error looks like you use an ancient version of mpd. We even supported 3.7 in 1.0.0. Is this maybe the old python-mpd?

**Comment by novski** [comment]
https://github.com/mrstegeman/mpd-webthing/issues/2#issuecomment-631043760

**Comment by Mic92** [comment]
Ok. This looks like a general connection issue. You can use netcat: `nc -v <ip> 6600`, where `<ip>` is the ip address of your MPD host. Make sure your firewall allows port 6600 or whatever you use as port.
