### ISSUE TITLE
Latest version is not uploaded to PyPI

### ISSUE THREAD

**Issue by Anubi85** [Mic92/python-mpd2#118]
The latest release (1.1.0) is not uploaded to PyPI. If you install the package via pip the latest available version is 1.0.0

**Comment by jameskirsop** [comment]
@Mic92, are you able to remedy this?? 8 Months later and we're still only seeing 1.0.0 on PyPi :(

**Comment by brunosmmm** [comment]
Any update on this?

**Comment by Mic92** [comment]
Done https://pypi.org/project/python-mpd2/1.1.0/#files
