### ISSUE TITLE
AF_UNIX only works for absolute paths

### ISSUE THREAD

**Issue by phryk** [Mic92/python-mpd2#120]
See https://github.com/Mic92/python-mpd2/blob/master/mpd/base.py#L645
Not sure if this is a bug, but a more general solution than `startswith('/')` would be nice.

I for example use `~/.mpd/socket` on my laptop and that won't be seen as AF_UNIX socket by python-mpd2. `'/' in host` might be a better solution, but also doesn't cover all cases since the socket file might also lie in the current directory, which then gets really murky to distinguish from a hostname.

Not sure how other clients handle this, but at least the `~/foo` notation works both with `mpc` and `ncmpcpp`.

**Comment by Mic92** [comment]
We need the trailing slash to distinguish between hostnames and socket paths.
Just use `os.path.expanduser(path)` before passing the socket path to MPD.

**Comment by phryk** [comment]
But that's my point –  we **don't** need the trailing slash as hostnames can't contain slashes. So `'/' in host` would be a better match for deciding whether something is a hostname.

**Comment by Mic92** [comment]
Distinguishing between a relative path and hostname is otherwise impossible without system calls.

**Comment by glen3b** [comment]
Alternatively, both a connect_tcp and connect_unix could be exposed (probably in addition to the already-existing connect), so this library doesn't have to determine type in all cases if the caller knows better.

**Comment by Mic92** [comment]
The thing is that even if it takes allows relative path than your `~/.mpd/socket` example won't work. It is also your shell that expands the path before passing the program. This library is not a shell. Adding to new methods for `connect_tcp`/`connect_unix` seems like an overkill and breaks user's code for little gain.
