### ISSUE TITLE
next() method kills playlist entry

### ISSUE THREAD

**Issue by JoergZ2** [Mic92/python-mpd2#122]
I've a list of internet radio stations stored in Radiostationen.m3u. Everytime I use the MPDClient.next() method the current entry is deleted from the playlist and one of the following entries ist played. But not that one which follows immediatly but one of the entries further below. Why is the starting entry to be deleted? Why is not used the next line in my station list? How can I manage to play the next station without fetching the current position value first and adding 1 and send back the new position with play() method? (That's my workaround ;-))
Btw: The previous() method does not kill any entry!
MPD server:
System: Raspberry Pi 3
OS-Version: Raspian Stretch
MPD version: 0.20.9

MPD client:
python-mpd2
Python version 3.8.2 on Ubuntu 20.04 LTS

EDIT: Solved! MPD server was running in consume mode.

**Comment by Mic92** [comment]
Problem was solved according to issue author.
