### ISSUE TITLE
Feature Request: allow empty FIND and SEARCH

### ISSUE THREAD

**Issue by JPT77** [Mic92/python-mpd2#129]
I am currently trying to simply find anything from the database but I simply don't understand the phrasing.
For me a solution would be, if without parameter the commands would return every track in the database.
thanks.

**Comment by pcwalden** [comment]
It has been awhile, but I do no think you can dump the whole database with one call. You have to use lsinfo(<path>) to get the content of each each directory. Also the root directory returns the list of playlists as well.

Excerpt from some code that browses the database:
```

            self.dirlist.append(self.mpd_client.lsinfo())
##          Remove any playlist entries from the database lsinfo() call
            for idx in range(len(self.dirlist[-1])):
                if 'playlist' in self.dirlist[-1][idx]:
                    break
            del self.dirlist[-1][idx:len(self.dirlist[-1])]
            self.listlen = len(self.dirlist[-1])
            self.index.append(0)
            self.path.append('')

```

**Comment by JPT77** [comment]
Thanks. I used the listall() method. I thought it required a parameter as well, which database to use. but it didn't. Without any parameters it returns everything (including dirs)
