### ISSUE TITLE
[Question] mpd.base.CommandError: [4@0] {noidle} you don't have permission for "noidle"

### ISSUE THREAD

**Issue by Schluggi** [Mic92/python-mpd2#165]
Hi,
I know this is probably not the best place for my problem. However, do not know what else I can do. I hope you guys can help me anyway.

As described [here](https://community.home-assistant.io/t/problem-with-the-mpd-integration-in-home-assistant-core/281321), I have a problem with Home Assistant and the mpd integration (which uses python-mpd2).  

I am getting this error in my home assistant log.  
```
mpd.base.CommandError: [4@0] {noidle} you don't have permission for "noidle"
```

As far as I know, the first step of an mpd connection is to connect to the mpd server (with an optional password).
If I change the password to something wrong, I get a different error. So the connection and authorization seem to work.
Is there another level of authorization? If so, what and how can I change this? And is this a client or a server issue?

**Comment by Mic92** [comment]
I am not aware of a second level of authorization. Maybe noidle is sent before the password is sent? @mweinelt 
The following command can dump if this is the case:

```
$ tcpdump -i any -n port 6600 -A
```

**Comment by mweinelt** [comment]
We don't explicitly send `noidle`.

```python
    async def _connect(self):
        """Connect to MPD."""
        try:
            await self._client.connect(self.server, self.port)

            if self.password is not None:
                await self._client.password(self.password)
        except mpd.ConnectionError:
            return
```

https://github.com/home-assistant/core/blob/4ab0151fb1cbefb31def23ba850e197da0a5027f/homeassistant/components/mpd/media_player.py#L118-L126

**Comment by Mic92** [comment]
Maybe you can help? @chrysn

**Comment by chrysn** [comment]
The idle command is implicitly sent with async operation when nothing has happened, and `noidle` pretty much as a precaution against race conditions.

It didn't occur to me that there could be any situation in which `noidle` is not accepted (not running MPD with passwords myself).

I can't write a patch right now (caught up in deadlines); if someone wants to have it faster than I get to it, look around when `__in_idle` is set. Might be a bug (more than just me not thinking of password authentication) somewhere, as the connect code doesn't look like it shoudl take IMMEDIATE_COMMAND_TIMEOUT long to execute, especially as it's only started after the hello has been exchanged.

**Comment by Schluggi** [comment]
Thanks @chrysn for the explanation. 

Strangely enough, the problem has just fixed itself.
Therefore this issue can be closed.

Big thanks for the support!

**Comment by Mic92** [comment]
> Thanks @chrysn for the explanation.
> 
> Strangely enough, the problem has just fixed itself.
> Therefore this issue can be closed.
> 
> Big thanks for the support!

Let's keep it open. It sounds like a race condition to me.
