### ISSUE TITLE
[feat-req] add all missing commands from mpc, minor improvement

### ISSUE THREAD

**Issue by ozone89** [Mic92/python-mpd2#168]
First thing first, thank you for the hard work you're putting into this project :D

As per title, it'd be nice to have the command set on par with `mpc`

List can be found here https://helpmanual.io/help/mpc/ or via `mpc help`

In particular, would be nice to have at least `cdprev` and `toggle`, as it would simplify some coding

as an example, I have managed to implement the former as

```
if float(client.status()['elapsed']) < 5:
        client.previous()
else:
        client.play(client.status()['song'])
```

also, little improvement would be to have the value of the fields returned as the proper type

**Comment by Mic92** [comment]
Are those also in the mpd protocol?

**Comment by Mic92** [comment]
I prefer to not make library more complex than necessary.
