### ISSUE TITLE
Code loosing connection

### ISSUE THREAD

**Issue by Schmeling-M** [Mic92/python-mpd2#171]
When I do this in my code:
`if Client.status()['state'] == "play":`

I get this:
Apr 14 08:34:14 moode systemd[1]: Stopped Music Player Daemon.
Apr 14 08:34:14 moode systemd[1]: Started Music Player Daemon.
Apr 14 08:34:14 moode rc.local[481]: Traceback (most recent call last):
Apr 14 08:34:14 moode rc.local[481]:   File "/home/pi/ampcontroller.py", line 196, in <module>
Apr 14 08:34:14 moode rc.local[481]:     if Client.status()['state'] == "play": # Playing or Airplay active
Apr 14 08:34:14 moode rc.local[481]:   File "/usr/local/lib/python3.7/dist-packages/mpd/base.py", line 469, in mpd_command
Apr 14 08:34:14 moode rc.local[481]:     return wrapper(self, name, args, callback)
Apr 14 08:34:14 moode rc.local[481]:   File "/usr/local/lib/python3.7/dist-packages/mpd/base.py", line 532, in _execute
Apr 14 08:34:14 moode rc.local[481]:     return retval()
Apr 14 08:34:14 moode rc.local[481]:   File "/usr/local/lib/python3.7/dist-packages/mpd/base.py", line 454, in command_callback
Apr 14 08:34:14 moode rc.local[481]:     res = function(self, self._read_lines())
Apr 14 08:34:14 moode rc.local[481]:   File "/usr/local/lib/python3.7/dist-packages/mpd/base.py", line 394, in _parse_object
Apr 14 08:34:14 moode rc.local[481]:     objs = list(self._parse_objects(lines))
Apr 14 08:34:14 moode rc.local[481]:   File "/usr/local/lib/python3.7/dist-packages/mpd/base.py", line 240, in _parse_objects
Apr 14 08:34:14 moode rc.local[481]:     for key, value in self._parse_pairs(lines):
Apr 14 08:34:14 moode rc.local[481]:   File "/usr/local/lib/python3.7/dist-packages/mpd/base.py", line 235, in _parse_pairs
Apr 14 08:34:14 moode rc.local[481]:     for line in lines:
Apr 14 08:34:14 moode rc.local[481]:   File "/usr/local/lib/python3.7/dist-packages/mpd/base.py", line 586, in _read_lines
Apr 14 08:34:14 moode rc.local[481]:     line = self._read_line()
Apr 14 08:34:14 moode rc.local[481]:   File "/usr/local/lib/python3.7/dist-packages/mpd/base.py", line 571, in _read_line
Apr 14 08:34:14 moode rc.local[481]:     raise ConnectionError("Connection lost while reading line")
Apr 14 08:34:14 moode rc.local[481]: mpd.base.ConnectionError: Connection lost while reading line
Apr 14 08:34:14 moode systemd[1]: rc-local.service: Control process exited, code=exited, status=1/FAILURE
Apr 14 08:34:14 moode systemd[1]: Created slice system-bluealsa\x2daplay.slice.
Apr 14 08:34:14 moode systemd[1]: Started BlueAlsa-Aplay.
Apr 14 08:34:14 moode systemd[1]: rc-local.service: Failed with result 'exit-code'.
Apr 14 08:34:14 moode systemd[1]: Failed to start /etc/rc.local Compatibility.

In the beginning of my code, I connect to mpd like so:
Client = mpd.MPDClient() # create client object
Client.timeout = None
Client.idletimeout = None

while True:
    try:
        Client.connect("localhost", 6600) # connect to localhost:6600
    except:
        continue
    break

It seems like I get a connection error, but how do I solve this, and why am I loosing the connection???

**Comment by Mic92** [comment]
Mpd is closing connections after a some timeout if your client is not doing anything. see https://github.com/Mic92/python-mpd2/issues/90

I cannot see the whole program so it is hard to tell what your pattern in the library is.

**Comment by Schmeling-M** [comment]
I'm starting the code from etc/rc.local, so it starts immediately, and the error likewise, it seems. I have set the timeouts  to none, So I wouldn't expect the connection to be closed that fast, but I might be wrong. The entire code is below:

# Import the libraries to use time delays, send os commands and access GPIO pins
import RPi.GPIO as GPIO
import time
import os
import mpd
import sys
import sqlite3 as SQLite3

# Setup Variables
PowerButtonPin = 7
KeepPoweredPin = 8 # Pin to pull high to keep the Pi Supply giving power
RedLedPin = 13 # Set pin number for "OFF" LED
RedExtLedPin = 16 # Set pin number for "OFF" LED
GreenLedPin = 15 # Set pin number for "ON" LED
GreenExtLedPin = 18 # Set pin number for "ON" LED
MainRelayPin = 11 # Set pin number for relay output
Debug = False # Set to true if you want debug from the program. Remember to set it to false if you start the script from rc.local, otherwise your promt will be junked
AmpState = "on" # Stores on/off/standby state of the player and amp
ButtonOverride = False # False except when button initiates standby.
ShutdownActive = False # True when system is shutting down.
TimeSinceActive = time.time() # Stores the time when MoOde was last active
StandbyTimeLimit = 60
OffTimeLimit = 120

# Setup GPIO pins
GPIO.setmode(GPIO.BOARD) # Set pin numbering to board numbering
GPIO.setup(MainRelayPin, GPIO.OUT, initial=GPIO.LOW) # Setup MainRelayPin as an output
#GPIO.setup(PowerButtonPin, GPIO.IN, pull_up_down = GPIO.PUD_DOWN) # Setup PowerButtonPin as an input
GPIO.setup(PowerButtonPin, GPIO.IN) # Setup PowerButtonPin as an input  
GPIO.setup(RedLedPin, GPIO.OUT) # Setup RedLedPin as an output
GPIO.setup(GreenLedPin, GPIO.OUT) # Setup GreenLedPin as an output
GPIO.setup(RedExtLedPin, GPIO.OUT) # Setup RedLedPin as an output
GPIO.setup(GreenExtLedPin, GPIO.OUT) # Setup GreenLedPin as an output  
GPIO.setup(KeepPoweredPin, GPIO.OUT, initial=GPIO.HIGH) #Setup KeepPoweredPin to pull high to keep the Pi Supply giving power


# Amplifier state control procedure
def SetAmpState(state):

    global AmpState
    
    GPIO.output(RedLedPin,False)
    GPIO.output(RedExtLedPin,False)
    GPIO.output(GreenLedPin,False)
    GPIO.output(GreenExtLedPin,False)

    if state == "on":
        GPIO.output(GreenLedPin,True)
        GPIO.output(GreenExtLedPin,True)
        GPIO.output(MainRelayPin, GPIO.HIGH)
        AmpState = "on"
        
    elif state == "off":
        GPIO.output(RedLedPin,True)
        GPIO.output(RedExtLedPin,True)
        GPIO.output(MainRelayPin, GPIO.LOW)
        AmpState = "off"
        #os.system("shutdown -h 0&")
        os.system("sudo shutdown now")
        #sys.exit("Amp was turned off")
        #sys.exit(0)
        
    elif state == "standby":
        GPIO.output(GreenLedPin,True)
        GPIO.output(GreenExtLedPin,True)
        GPIO.output(RedLedPin,True)
        GPIO.output(RedExtLedPin,True)
        GPIO.output(MainRelayPin, GPIO.LOW)
        Client.pause(1)
        AmpState = "standby"
        # Mute Moode player
        #os.system("/var/www/vol.sh mute")
            
    if (Debug): print("Amplifier state: {0}".format(AmpState))
    
    
# Airplay state check
def IsAirplayOn():
    
    global ButtonOverride
    
    AirplayOn = False
    try:
        cur = con.cursor()    
        cur.execute('select value from cfg_system where param=\'airplayactv\'')
        data = cur.fetchone()[0]    
        if (Debug): print("SQL = %s" % data)
        if data == "1":
            AirplayOn = True

    except SQLite3.Error as e:
        if (Debug): print("Error %s:" % e.args[0])

    if ButtonOverride:
        AirplayOn = False
    
    if Debug: print("Returning IsAirplayOn = {0}".format(AirplayOn))
    return AirplayOn    

    
def Eval_buttonpress(channel):
    global ShutdownActive
    global ButtonOverride
    global TimeSinceActive
    
    # only react when there is no other shutdown process running
    if not ShutdownActive:
        ShutdownActive = True
        pressed = 1
        counter = 0
        while (pressed == 1):
            if (GPIO.input(PowerButtonPin) == True):
                # button is still pressed
                counter = counter + 1
                if (Debug): print(("Counter is now: {0}".format(counter)))
                # break if we count beyond 20 (long-press is a shutdown)
                if (counter >= 20):
                    pressed = 0
                else:
                    time.sleep(0.2)
            else:
                # button has been released
                pressed = 0
        
        if (Debug): print(("Button was pressed for: {0} counts.".format(counter)))
        
        # count how long the button was pressed
        if (counter < 2):
            # short press
            pressed = 0
            ShutdownActive = False
        else:
            if (counter < 20):
                # medium length press
                if (Debug): print("Muting Moode..")
                if AmpState == "on":
                    SetAmpState("standby")
                    ButtonOverride = True
                else:
                    SetAmpState("on")
                    ButtonOverride = False
                    TimeSinceActive = time.time()
                pressed = 0
                ShutdownActive = False
            else:
                # long press, initiate system shutdown
                if (Debug): print("shutting down..")
                SetAmpState("off")
                pressed = 0
    #ShutdownActive = False
    pressed = 0


# Setup MDPClient and connect to MPD on localhost
Client = mpd.MPDClient() # create client object
Client.timeout = None
Client.idletimeout = None

while True:
    try:
        Client.connect("localhost", 6600) # connect to localhost:6600
    except:
        continue
    break

    
# Connect to player database, in order to read Airplay status     
try:
        con = SQLite3.connect('/var/local/www/db/moode-sqlite3.db')    
except SQLite3.Error as e:
        if Debug: print("Error %s:" % e.args[0])
        sys.exit(1)


# Set PowerButtonPin as an interrupt input
GPIO.add_event_detect(PowerButtonPin, GPIO.RISING, callback = Eval_buttonpress)

SetAmpState("on")
#TimeSinceActive = time.time()

#global ButtonOverride
#global TimeSinceActive
#global AmpState
#global ShutdownActive

time.sleep(20)

TimeSinceActive = time.time()

# main loop
while True:
    ElapsedTime = time.time() - TimeSinceActive
    if (Debug): print(("{0} seconds have passed since last MPD was last playing.".format(ElapsedTime)))    
        
#    if Client.status()['state'] == "play" or IsAirplayOn(): # Playing or Airplay active
    if Client.status()['state'] == "play": # Playing or Airplay active
        ButtonOverride = False
        StandbyTimeLimit = 240
        OffTimeLimit = 600
        TimeSinceActive = time.time()
        if not AmpState == "on" and ShutdownActive == False:
            SetAmpState("on") # Set GPIO pins to ON state
            if (Debug): print("MPD state = play! Entering ON state")
            if (Debug): print(("Amp is on = {0}".format(GPIO.input(MainRelayPin))))

    else: # Either stopped or paused

        if ElapsedTime >= StandbyTimeLimit:
            if AmpState == "on":
                SetAmpState("standby") # Set GPIO pins to OFF state
                if (Debug): print(("MPD has not been playing for {0} seconds! Entering standby!".format(ElapsedTime)))
                if (Debug): print(("Amp is on = {0}".format(GPIO.input(MainRelayPin))))

        if ElapsedTime > OffTimeLimit:
            if AmpState == "standby":
                SetAmpState("off") # Set GPIO pins to OFF state
                if (Debug): print(("MPD has not been playing for {0} seconds! Shutting down!".format(ElapsedTime)))
                if (Debug): print(("Amp is on = {0}".format(GPIO.input(MainRelayPin))))

    time.sleep(0.1)


# Close connection to MPD (not used since the main loop never exits)
Client.close() # send the close command
Client.disconnect() # disconnect from the server

# Close connection to database
if con:
    con.close()

**Comment by Mic92** [comment]
Sorry this is not readable without proper indentation. If you could upload a repo or gist, I might have a look...

**Comment by Schmeling-M** [comment]
Yes, terribly sorry about that. I uploaded a gist instead. It seems to be working. Please let me know if it doesn't.

https://gist.github.com/Schmeling-M/3be163d0bf6fb3ac520df6dd9dc8ed54

One thing, that especially pussels me is that the raised exception in base.py, line 571 is raised because of this condition in line 569:  if not line.endswith("\n"): Is this because the lack of "\n" means, that the connection to mpd is lost or.....?

**Comment by Mic92** [comment]
If read returns an empty string, this is detected as connection lost.

I cannot see any obvious bug right now, but maybe check if the following code works for your:

```python
import logging, mpd
logging.basicConfig(level=logging.DEBUG)
client = mpd.MPDClient()
client.connect("localhost", 6600)
print(client.status())
```

**Comment by Schmeling-M** [comment]
I take it, your suggestion doesn't solve the problem. Only debugs it further, correct?

**Comment by Mic92** [comment]
Is mpd actually listening on this port?

You can run tcpdump to see what is going on the wire:

```
$ sudo tcpdump -i any localhost port 6600 -v -A
```

And than run in another terminal, the same script.

**Comment by Mic92** [comment]
Also I would not run this code anywhere where untrusted clients have access to:
It is full of shell injection bugs: https://github.com/moode-player/moode/blob/653bbb46f44851050e74a5c86693603ad9c14ea7/www/command/moode.php#L272

**Comment by Schmeling-M** [comment]
Thankyou for all the suggestions and feedback. I'll test the connection in the following days, and see, if that might be the problem.

Fortunately the player is on a private lan. No untrusted clients have access.

**Comment by Schmeling-M** [comment]
It seems, I have a connection to mpd. At least I get the correct info, when running your python code:
this
`import logging, mpd
logging.basicConfig(level=logging.DEBUG)
client = mpd.MPDClient()
client.connect("localhost", 6600)
print(client.status())`

gives this
`root@moode:/home/pi# python3 mpd_test.py
INFO:mpd.base:Calling MPD connect('localhost', 6600, timeout=None)
DEBUG:mpd.base:Calling MPD status()
{'volume': '0', 'repeat': '0', 'random': '0', 'single': '0', 'consume': '0', 'partition': 'default', 'playlist': '2', 'playlistlength': '3', 'mixrampdb': '0.000000', 'state': 'play', 'song': '1', 'songid': '2', 'time': '979:1550', 'elapsed': '979.219', 'bitrate': '192', 'duration': '1550.294', 'audio': '44100:24:2', 'nextsong': '2', 'nextsongid': '3'}`

So I'm guessing, the connection works initially, but with timeout set to none, I cant see why the connection i suddenly lost??

**Comment by Schmeling-M** [comment]
my mpd config /etc/mpd.conf looks like so:
`root@moode:/etc# cat mpd.conf
#########################################
This file is automatically generated
by the MPD configuration page.
#########################################

music_directory "/var/lib/mpd/music"
playlist_directory "/var/lib/mpd/playlists"
db_file "/var/lib/mpd/database"
log_file "/var/log/mpd/log"
pid_file "/var/run/mpd/pid"
state_file "/var/lib/mpd/state"
sticker_file "/var/lib/mpd/sticker.sql"
user "mpd"
group "audio"
bind_to_address "any"
port "6600"
log_level "default"
restore_paused "yes"
auto_update "no"
follow_outside_symlinks "yes"
follow_inside_symlinks "yes"
zeroconf_enabled "no"
zeroconf_name "Moode MPD"
filesystem_charset "UTF-8"
metadata_to_use "+comment"
replaygain "off"
replaygain_preamp "0"
volume_normalization "no"
audio_buffer_size "4096"
max_output_buffer_size "131072"
max_playlist_length "16384"
max_connections "128"

decoder {
plugin "ffmpeg"
enabled "yes"
}

input {
plugin "curl"
}

resampler {
plugin "soxr"
quality "high"
threads "1"
}

audio_output {
type "alsa"
name "ALSA Default"
device "hw:0,0"
mixer_type "software"
dop "no"
}

audio_output {
type "alsa"
name "ALSA Crossfeed"
device "crossfeed"
mixer_type "software"
dop "no"
}

audio_output {
type "alsa"
name "ALSA Parametric EQ"
device "eqfa12p"
mixer_type "software"
dop "no"
}

audio_output {
type "alsa"
name "ALSA Graphic EQ"
device "alsaequal"
mixer_type "software"
dop "no"
}

audio_output {
type "alsa"
name "ALSA Polarity Inv"
device "invpolarity"
mixer_type "software"
dop "no"
}

audio_output {
type "alsa"
name "ALSA CamillaDSP"
device "camilladsp"
mixer_type "software"
dop "no"
}

audio_output {
type "alsa"
name "ALSA Bluetooth"
device "btstream"
mixer_type "software"
}

audio_output {
type "httpd"
name "HTTP Server"
port "8000"
encoder "lame"
bitrate "320"
tags "yes"
always_on "yes"
}

root@moode:/etc#
`

**Comment by Mic92** [comment]
timeout is already None by default... you don't even need to set it.

**Comment by Schmeling-M** [comment]
I think I found the problem. If I run this code:

https://gist.github.com/Schmeling-M/ae67c0b82f804dfcf65bc3f8a4d0081e

It runs perfectly, until I connect to moode via bluetooth, in which case, it spits out exactly the same error as before

DEBUG:mpd.base:Calling MPD status()
DEBUG:mpd.base:Calling MPD status()
{'volume': '0', 'repeat': '0', 'random': '0', 'single': '0', 'consume': '0', 'partition': 'default', 'playlist': '2', 'playlistlength': '7', 'mixrampdb': '0.000000', 'state': 'play', 'song': '6', 'songid': '7', 'time': '335:335', 'elapsed': '334.685', 'bitrate': '32', 'duration': '334.889', 'audio': '44100:24:2'}
DEBUG:mpd.base:Calling MPD status()
DEBUG:mpd.base:Calling MPD status()
{'volume': '0', 'repeat': '0', 'random': '0', 'single': '0', 'consume': '0', 'partition': 'default', 'playlist': '2', 'playlistlength': '7', 'mixrampdb': '0.000000', 'state': 'play', 'song': '6', 'songid': '7', 'time': '335:335', 'elapsed': '334.788', 'bitrate': '32', 'duration': '334.889', 'audio': '44100:24:2'}
DEBUG:mpd.base:Calling MPD status()
DEBUG:mpd.base:Calling MPD status()
INFO:mpd.base:Calling MPD disconnect()
Traceback (most recent call last):
  File "mpd_test2.py", line 15, in <module>
    print(client.status())
  File "/usr/local/lib/python3.7/dist-packages/mpd/base.py", line 469, in mpd_command
    return wrapper(self, name, args, callback)
  File "/usr/local/lib/python3.7/dist-packages/mpd/base.py", line 532, in _execute
    return retval()
  File "/usr/local/lib/python3.7/dist-packages/mpd/base.py", line 454, in command_callback
    res = function(self, self._read_lines())
  File "/usr/local/lib/python3.7/dist-packages/mpd/base.py", line 394, in _parse_object
    objs = list(self._parse_objects(lines))
  File "/usr/local/lib/python3.7/dist-packages/mpd/base.py", line 240, in _parse_objects
    for key, value in self._parse_pairs(lines):
  File "/usr/local/lib/python3.7/dist-packages/mpd/base.py", line 235, in _parse_pairs
    for line in lines:
  File "/usr/local/lib/python3.7/dist-packages/mpd/base.py", line 586, in _read_lines
    line = self._read_line()
  File "/usr/local/lib/python3.7/dist-packages/mpd/base.py", line 571, in _read_line
    raise ConnectionError("Connection lost while reading line")
mpd.base.ConnectionError: Connection lost while reading line
root@moode:/home/pi#

So it seems that the error is natural, but why it occurs at startup, when I run the script from etc/rc.local I do not know.It could perhaps be because bluetooth forces an mpd disconnect, but I'm not sure.

Do you have any idea, as to why this might be happening?

**Comment by Mic92** [comment]
not really no.

**Comment by Mic92** [comment]
I don't really see any actionable insights on what is broken here in the library. This seems more a setup issue.
