### ISSUE TITLE
How to use noidle?

### ISSUE THREAD

**Issue by artur-shaik** [Mic92/python-mpd2#185]
I just don't get it. Docs says I can use `noidle` command, but it returns: `NotImplementedError: Abstract MPDClientBase does not implement noidle`.

**Comment by Mic92** [comment]
This currently only works properly with asyncio: https://github.com/Mic92/python-mpd2/blob/4c1e6a87748b0b0e4cb9839f9b59056e64e2f9ff/examples/asyncio_example.py#L55

**Comment by artur-shaik** [comment]
Ok, thanks. Seems like docs should be updated.

**Comment by Mic92** [comment]
Be my guest.
