### ISSUE TITLE
How to avoid the large flow in the infinite loop

### ISSUE THREAD

**Issue by Ocyss** [Mic92/python-mpd2#215]
I plan to display the lyrics in my bar, so I wrote an infinite loop to get the current time, and then query the corresponding words to print.

But I found that the traffic ran to 50MB/s, and I don't know how to avoid it. I think ncmpcpp should also read more frequently. I don't know how they communicate. I read the documentation of mpd2, but it didn't solve my problem.

**Comment by Mic92** [comment]
Can you not synchronize the time in the client and only infrequently update the time from mpd for synchronization?

**Comment by Ocyss** [comment]
I currently use two threads, one to output the lyrics in an infinite loop, and the other to get the time + process the current lyrics in an infinite loop, but add a sleep of 0.5 seconds, this problem is solved.
