### ISSUE TITLE
asyncio port

### ISSUE THREAD

**Issue by chrysn** [Mic92/python-mpd2#30]
python-mpd could be ported to asyncio (tulip), which would make it easy to integrate in a multitude of main loops from web servers to guis.

i've started porting, and have the very basics running (tcp connection, not blocking on connection and issuing basic commands, integration in gtk3 using gbulb), but it's only a small part. (haven't touched unix sockets (should be trivial) or idle (should interact greatly); `iterate` mode would have to be standard in this mode, even if it's not exposed).

i'm not sure yet where this takes the code base. my changes so far are small, but i don't think it's feasible to have `if`s everywhere around to keep the same code working both blockingly and via asyncio. it might be possible to provide a blocking mode from that code base (where every blocking call is a thinly wrapped nonblocking call), but unless the python2.7 backport makes progress, that'll be python3.3+ only anyway.

(porting to asyncio is just starting, so patterns for keeping both a classical and an asynchronous interfaces can be expected to show up. let's see where this goes.)

this is currently an "i spend an hour on it when i need a break" project for me, so if you want to see progress soon, you'll have to join in or wait for me to be bored with everything else again :-)

**Comment by chrysn** [comment]
With three years of asyncio programming experience and the changes between Python 3.3 and Python 3.6, this has become a much smoother ride. I've started work on this issue again, basics are working, branch is on its way.

**Comment by rnixx** [comment]
@chrysn have you based you work on recent master? in the meantime then code has been refactored to provide a basic protocol, the default sync version of the protocol and a twisted version. maybe you can add an asyncio based one in asyc.py or so...

**Comment by chrysn** [comment]
> @chrysn have you based you work on recent master?

i've started from scratch, and yes, on the recent master.

right now -- as opposed to back then -- it's just a module with no code
changes to the base, and thus far from the 2014 intrusiveness.

i expect that i'll create a pull request for the plain asyncio.py
module, and then one to remove some workarounds by eg. adding a

    _parse_objects_direct = _parse_objects

method in BaseMPDClient, and changing all `return self._parse_objects`
to `return self._parse_objects_direct` (maybe with an additional keyword
tag to mpd_commands) so that async has a cleaner override point.

**Comment by rnixx** [comment]
@chrysn you might want to have a look how the twisted version is implemented. There's no need to change the BaseMPDClient IMHO.

**Comment by chrysn** [comment]
> @chrysn you might want to have a look how the twisted version is implemented. There's no need to change the BaseMPDClient IMHO.

@Mic92: my twisted-fu is weak, so i can't tell easily: does the twisted
version give an interface that allows applications to receive songs in a
long list as they come in, or does it only return a big list/iterable
when complete? (the former is easy w/o modifications too, the latter
would profit from the small changes i suggested)

**Comment by chrysn** [comment]
Oups, the @-mention in the above post should have gone to @rnixx (looked at the wrong mail header). Can you tell me whether the twisted implementation can feed objects (eg. songs) to the application before the response has been completed? (If yes, I don't understand how it does that; if not, that's why the asyncio binding wants some extensions).

**Comment by rnixx** [comment]
@chrysn - sry for the late reply

> Can you tell me whether the twisted implementation can feed objects (eg. songs) to the application before the response has been completed?

Not it does not. It collects the result and calls the deferred (aka future) once the complete result is received.

How do you handle concurrent access to the same connection? Do you always open a new TCP/Socket connection for each "task"? Or do you have some other mechanism preserving a sane state? Or is this left to the user?

**Comment by chrysn** [comment]
> No it does not

Thanks – that explains then why I'd like to have some more changes in mpd.base than twisted needed.

> do you have some other mechanism preserving a sane state? Or is this left to the user?

@rnixx: I have an asyncio.Task (`self.__run_task = asyncio.Task(self.__run())`) that waits to pop items from the command queue, sends the attached command to the server and feeds all lines til the next OK (or any errors) to the item which is a Future that in the course of the lines gets done. (These items are called "results" due to this, maybe CommandInstance would be more suitable).

Some CommandResult items (the CommandResultIterable) are not only a future but also an asynchronous iterable, but that's something __run doesn't directly need to concern itself with.

Furthermore (and that's why it is almost 50 LoC), `__run` also schedules an `idle` on the currently relevant subsystems (so multiple idle with different interests can run concurrently from the library user's point of view) and interrupts with `noidle` when a command comes along or the idle interests change.
