### ISSUE TITLE
Creating empty persistent playlists

### ISSUE THREAD

**Issue by rnixx** [Mic92/python-mpd2#51]
Is it possible to create a new persistent empty playlist?

**Comment by mxjeff** [comment]
I believe the protocol have all it needs to do so:

http://www.musicpd.org/doc/protocol/playlist_files.html

**Comment by rnixx** [comment]
what i did now is

client.clear()
client.save(playlist_name)

for creating new empty lists.

client.playlistadd(name, uri) won't do the job because URI must not be empty

this solution is not optimal because mpd stops playing after current track when creating new playlists

**Comment by mxjeff** [comment]
Well, you can still use playlistadd with an **empty** URI:
```python
client.playlistadd("empty", "")
```
But then I noticed MPD is waving a playlist with all library in it.
You can then empty the playlist.
```python
cli.playlistclear("empty")
```
That way your not interfering with current queue with `clear`, `save` commands, mpd will not stop playing then.

**Comment by rnixx** [comment]
just tried. that did the trick. thanks!
