### ISSUE TITLE
How to wait until update database is complete?

### ISSUE THREAD

**Issue by swprojects** [Mic92/python-mpd2#57]
Is it possible to wait until MPDclient().update() is complete?

i.e. mpc update --wait

**Comment by pcwalden** [comment]
Here is a code excerpt you might use:

                    MPD2.send_idle()
                    # do this periodically, e.g. in event loop
                    canRead = select([MPD2], [], [])[0]
                    if canRead:
                        event = MPD2.fetch_idle()
                if 'database' in event: # exit wait loop

**Comment by swprojects** [comment]
Thanks, will give this a go.
