### ISSUE TITLE
currentsong() does not return song title

### ISSUE THREAD

**Issue by jhdulaney** [Mic92/python-mpd2#60]
It appears that currentsong() does not return the song's title, just the file name (as well as other useful bits of information), or am I just using it wrong?

**Comment by Mic92** [comment]
Depends on the file, if it has additional metadata such as idv3-tags:

```
currentsong
file: podcasts/pandroid/pandroid38.mp3
Last-Modified: 2015-02-04T10:19:44Z
Artist: Falko & Dirk
Title: PD038 - Cardboard
Album: Pandroid
Track: 38
Date: 2014
Genre: Speech
Time: 7515
Pos: 2
Id: 3
OK
```

**Comment by jhdulaney** [comment]
Ah, my apologies, I was looking at a bad example.  Thanks!
