### ISSUE TITLE
[Python 3.4] When used on windows \r\n is written instead of \n

### ISSUE THREAD

**Issue by 3onyc** [Mic92/python-mpd2#62]
Suspect the cause is `self._sock.makefile(...)`, file objects on Windows automatically convert `\n` into `\r\n`

**Comment by Mic92** [comment]
Hi. Can you show a minimal example, where something breaks on your system?

**Comment by 3onyc** [comment]
Relevant documentation
> When writing output to the stream, if newline is None, any '\n' characters written are translated to the system default line separator, os.linesep. If newline is '' or '\n', no translation takes place. If newline is any of the other legal values, any '\n' characters written are translated to the given string.

*Source: https://docs.python.org/3.4/library/functions.html#open*

---

Code
```python
from mpd import MPDClient

c = MPDClient()
c.connect("192.168.0.50", 6600)
c.setvol(25)
```

---

Transmitted
```
0000   73 65 74 76 6f 6c 20 22 32 35 22 0d 0a   setvol "25"\r\n
```

0d = CR
0a = LF

>The client transmits a command sequence, terminated by the newline character \n. The server will respond with one or more lines, the last of which will be a completion code. 

*Source: http://www.musicpd.org/doc/protocol/syntax.html#idp35362432*

---

This only occurs on Windows, and even though `setvol` works, CRLF instead of LF [caused issues](http://bugs.musicpd.org/view.php?id=3854) in other libraries.

**Comment by 3onyc** [comment]
In Python 3.x using self._sock.makefile(newline='\n') fixes this, but that does not exist in Python 2.

Another option is using binary mode instead of text mode, but (at least) in Python 3 you need to convert to bytes before writing.

**Comment by Mic92** [comment]
Thanks for researching on this topic.
We have conditional statement for python3 any way, when creating these objects.
Could you test this fix? https://github.com/Mic92/python-mpd2/tree/windows-linebreak-fix

**Comment by 3onyc** [comment]
```
0000   73 65 74 76 6f 6c 20 22 32 35 22 0a   setvol "25"\n
```
Seems fixed, thanks! (Might want to add a unit test)

**Comment by Mic92** [comment]
Actually I want to skip integration testing for simplicity. Maybe I could write/read from the same socket in process.
