### ISSUE TITLE
Insufficient Documentation for Status

### ISSUE THREAD

**Issue by blauertee** [Mic92/python-mpd2#66]
It would be great if you could add an explanation of dict returned by ```MPDClient.status()``` because I really do not understand the difference between ```MPDClient.status()['time']``` and ```MPDClient.status()['elapsed']```. And is there no way to get the absolute length of a song in seconds?

**Comment by Mic92** [comment]
try: 

```
current, end = MPDClient.status()['time'].split(":") 
```

instead of what your using.

**Comment by blauertee** [comment]
Thank you very much!
