### ISSUE TITLE
CommandError MPDClient.seekcur

### ISSUE THREAD

**Issue by blauertee** [Mic92/python-mpd2#67]
The MPDClient.seekcur function always raises the following:

```python
mpc.seekcur(60)
Traceback (most recent call last):
  File "<pyshell#33>", line 1, in <module>
    mpc.seekcur(60)
  File "/usr/local/lib/python2.7/dist-packages/mpd.py", line 600, in decorator
    return wrapper(self, name, args, bound_decorator(self, returnValue))
  File "/usr/local/lib/python2.7/dist-packages/mpd.py", line 238, in _execute
    return retval()
  File "/usr/local/lib/python2.7/dist-packages/mpd.py", line 595, in decorator
    return function(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mpd.py", line 363, in _fetch_nothing
    line = self._read_line()
  File "/usr/local/lib/python2.7/dist-packages/mpd.py", line 275, in _read_line
    raise CommandError(error)
CommandError: [5@0] {} unknown command "seekcur"
```

**Comment by Mic92** [comment]
Strange, do you have a very old mpd version?
Coud you try the following with netcat?

```
echo "commands" | nc -v localhost 6600
```

**Comment by blauertee** [comment]
Thank you for your fast answer!

It's a bit weired when I execute the command you suggested, I get: 
```
OK MPD 0.16.0
command: add
command: addid
command: clear
```
... No seekcur

And of course 0.16.0 is an Old version. Then I did tried to update using the official RPi sources but it told me that I'm on the newest version. So I downloaded the latest mpd source code and compiled it. ```mpd --version``` Says that I'm on 0.19.12 but when I execute your command the first line still is ```OK MPD 0.16.0```, no seekcur.

Strange!

I'll just use seek and get the current song position from status.

**Comment by Mic92** [comment]
which means, the old version is still running.

**Comment by blauertee** [comment]
Yeah, thats what I figured. Thanks for helping!

**Comment by Mic92** [comment]
You are welcome.
