### ISSUE TITLE
correct syntax for find?

### ISSUE THREAD

**Issue by mph070770** [Mic92/python-mpd2#70]
I'm using mpd2 along with PiMusicBox to control Spotify on a Rpi. I'm struggling to get good search results back from Spotify via MPD. I do the following

for a specific track by a specific artist
```
result = client.find("artist", artist_to_find, "title", track_to_find)
```

or just for an artist:
```
result = client.find("artist", artist_to_find)
```

The artist/track search usually gets results but the artist only search often returns nothing - even if the search (artist_to_find) is something like "David Bowie". 

Can anyone advise the best way to get Spotify results via MPD?

Thanks

**Comment by Mic92** [comment]
You mean Mopidy not MPD. Mopidy claims to be compatible, but I have never looked at that.
