### ISSUE TITLE
status(): I/O operation on closed file.

### ISSUE THREAD

**Issue by happyleavesaoc** [Mic92/python-mpd2#71]
Hi, I think this issue is related to some of the others (#31, #64). After some time of working great, I consistently get this exception:

```
  File "example.py", line 90, in update
    self.status = self.client.status()
  File "mpd.py", line 629, in decorator
    return wrapper(self, name, args, bound_decorator(self, returnValue))
  File "mpd.py", line 252, in _execute
    self._write_command(command, args)
  File "mpd.py", line 279, in _write_command
    self._write_line(" ".join(parts))
  File "mpd.py", line 258, in _write_line
    self._wfile.write("%s\n" % line)
ValueError: I/O operation on closed file.
```

It is connected to a `mopidy` instance, which continues to function. I suspect the connection is broken, but I'm not sure if `mpd2` should handle this, or I should proceed like the users in the referenced issues and reconnect myself.

**Comment by Mic92** [comment]
we had this discussion in #31, with the current synchronous api it is hard to implement custom error logic, which fits everyone's need. You may find this wrapper useful: https://github.com/schamp/PersistentMPDClient

**Comment by happyleavesaoc** [comment]
Ok, thanks for the confirmation! I'll handle the error in my application code.
