### ISSUE TITLE
support bytes string in python3?

### ISSUE THREAD

**Issue by rbn42** [Mic92/python-mpd2#72]
Hello,
Song information may be or not be encoded as UTF-8 string, and as I know, mpd does not convert them into UTF-8. So would it be better not forcing UTF-8 encoding in python3?
I did this for python3 in my own branch.

**Comment by Mic92** [comment]
The protocol specification says: "All data between the client and the server is encoded in UTF-8"

http://git.musicpd.org/cgit/cirrus/mpd.git/plain/doc/protocol.xml

If you find a counter example, please open an bug report on mpd's bug tracker.

**Comment by rbn42** [comment]
Oh sorry, you are right, I cannot find out any other encodings used by mpd. I see what is the problem now. mpd does encode data in UTF-8, but I still get UTF-8 conversion error in python3. I guess that is because mpd chooses wrong encoding to decode the raw data.

**Comment by Mic92** [comment]
On what system is your mpd running? Some people on windows have problems regarding filesystem encoding.

**Comment by rbn42** [comment]
I am on Ubuntu 16.04, and the filesystem is ext4. One of the song is a wav file. ncmpcpp also cannot display the song name (not the wav file name) correctly.
