### ISSUE TITLE
Missing text in auto-generated commands documentation

### ISSUE THREAD

**Issue by 3onyc** [Mic92/python-mpd2#74]
The commands documentation is currently missing any lists present in the description of a function, for example in [MPDClient.idle()](http://pythonhosted.org/python-mpd2/topics/commands.html#MPDClient.idle) there should be a list of subsystems.

**Comment by Mic92** [comment]
the script does not process <itemizedlist> at the moment: http://git.musicpd.org/cgit/cirrus/mpd.git/plain/doc/protocol.xml

**Comment by Mic92** [comment]
fixed
