### ISSUE TITLE
Key error: 'time' or Key error 'elapsed' ?

### ISSUE THREAD

**Issue by mobilisinuk** [Mic92/python-mpd2#78]
Hi
probably not a bug but i'm using 0.5.5 and client status do no seem to report time or elapsed on a mpd 0.16 server?
Also client.status()['time'] or client.status()['elapsed'] return a KeyError: 'time' or KeyError: 'elapsed'

could you please clarify the usage or is it a limitation of the versions Im using atm.
a command line mpc status return the expected value: for ex 0:05/7:40 (1%)
mpc status
www.litteratureaudio.com -
[playing] #1/6   0:05/7:40 (1%)
volume: 45%   repeat: on    random: off   single: off   consume: off

See satus below:
status= {'songid': '2038', 'playlistlength': '6', 'playlist': '2496', 'repeat': '1', 'consume': '0', 'mixrampdb': '0.000000', 'random': '0', 'state': 'stop', 'xfade': '0', 'volume': '45', 'single': '0', 'mixrampdelay': 'nan', 'nextsong': '1', 'song': '0', 'nextsongid': '2039'}
Traceback (most recent call last):
  File "radiotilt0.4.py", line 250, in <module>
    end = client.status()['time'].split(":")
KeyError: 'time'

regards
Mobilis

**Comment by Mic92** [comment]
Hi, I think you will have more success with `currentsong` instead of `status`:

```
$ nc -v localhost 6600
Connection to localhost 6600 port [tcp/*] succeeded!
OK MPD 0.19.0
status
volume: -1
repeat: 0
random: 0
single: 0
consume: 1
playlist: 2
playlistlength: 2
mixrampdb: 0.000000
state: stop
song: 1
songid: 2
OK
currentsong
file: podcasts/Binaergewitter/2016-09-01.Binaergewitter.Talk.156.mp3
Last-Modified: 2016-09-07T11:38:01Z
Artist: Binärgewitter-Team
Title: Binärgewitter Talk #156: Blitzschutzfilter
Album: Binärgewitter
Track: 156
Date: 2016
Time: 6615
Pos: 1
Id: 2
OK
```

**Comment by mobilisinuk** [comment]
Hi thx for your quick answer.
sorry what Im trying to obtain is the elapsed time in a file in order to "bookmark" the position and later to come to the same place. this is mainly while playing audio book or large mp3. the variable Time obtained via currentsong() seems to be invariant and actually the lenght of the file in seconds?

{'album': 'Livres audio gratuits', 'artist': 'www.litteratureaudio.com', 'track': '1', 'pos': '0', 'last-modified': '2016-11-01T22:45:56Z', 'file': 'books/Jules_Verne_-_Voyage_au_centre_de_la_Terre_Chap01.mp3', '**time**': '**460**', 'genre': 'Romans', 'id': '2147'}

again I could use mpc via subprocess as it provides this info about the current position in the file.
[playing] #1/6 **0:05/7:40 (1%)**
volume: 45% repeat: on random: off single: off consume: off
however I would like to know if MPD2 can obtained the same thing?

best regards
Mobilis

**Comment by Mic92** [comment]
If mpd is in the state "stop" as in the example above, there is no "elapsed" key in the output of status.
Even mpc does not report any progress:

```bash
$ mpc play
Adam Stacoviak & Andrew Thorp on 5by5.tv - The Changelog #125: Jekyll with Parker Moore
[playing] #4/7   0:42/73:35 (0%)
volume:100%   repeat: off   random: off   single: off   consume: on
$ mpc status
Adam Stacoviak & Andrew Thorp on 5by5.tv - The Changelog #125: Jekyll with Parker Moore
[playing] #4/7   1:00/73:35 (1%)
volume:100%   repeat: off   random: off   single: off   consume: on
$ mpc stop
volume:100%   repeat: off   random: off   single: off   consume: on
$ mpc status
volume: n/a   repeat: off   random: off   single: off   consume: on
```

You can only obtain progress from paused songs. 
What you can do, is periodically polling the status of a song and if it is stopped by the user, then store the last checked progress plus the time which has been passed since then. To get state changes the idle api of mpd is probably useful. I built a similar application in the past: https://github.com/Mic92/mpdstated

However it might be buggy with newer versions of MPD, because mpd kills connection in idle state, if there is no traffic for a certain amount of time.
