### ISSUE TITLE
client.status() does not report nextsong or nextsongid

### ISSUE THREAD

**Issue by grinder1000** [Mic92/python-mpd2#80]
I am sorry if i am missing something very obvious but according to the docs , client.status() should return the next song and the nextsongid. If these have been deprecated, could someone point me in the right direction on how (when the playlist is in random mode) to pick a song from the current playlist and get it to play immediately.

**Comment by Mic92** [comment]
MPD does only return `nextsongid`, if there is a next song in the current playlist. If there is only one file in the queue or the last track of the list is played, then this field is not set.
