### ISSUE TITLE
Volume command

### ISSUE THREAD

**Issue by jpstotz** [Mic92/python-mpd2#86]
I noticed that python-mpd2 misses the `volume` command which allows to change the volume relative (e.g +1/-1). I am still using v0.5.5 from pypy therefore I edited this version in my environment. I just added the volume command and afterwards `mpd_client.volume("-10")` was working without problems (tested with mpd  0.19.1). 

Unfortunately v0.5.5 and the current version are looking totally different and I want to stay with the stable version, but I think it would be a good idea to add the volume command in the current version.

**Comment by Mic92** [comment]
`volume` was already removed in [0.4.4](https://github.com/Mic92/python-mpd2/blob/master/doc/changes.rst#changes-in-041)

**Comment by dreieinhalb** [comment]
+1 for re-implementing `volume` in python-mpd2

[Commit for remove in mpd](https://github.com/MusicPlayerDaemon/MPD/commit/206392ad1a9f4aa22d11719fb19f036c9f860272)
[Commit for re-add in mpd](https://github.com/MusicPlayerDaemon/MPD/commit/961c7d0f7853d28eddffd74d4a874c3e6a85ee9c)

**Comment by Mic92** [comment]
https://github.com/Mic92/python-mpd2/pull/114
