### ISSUE TITLE
Is a threading lock needed in twisted.py

### ISSUE THREAD

**Issue by relevitt** [Mic92/python-mpd2#94]
In twisted.py, the lineReceived method and the _execute method both have a lock decorator. Why is a lock needed? Execution of everything in this module should occur in the main thread. Otherwise, if a lock were needed, execution would block, which is the outcome to be avoided in a twisted app.

**Comment by Mic92** [comment]
cc @rnixx

**Comment by rnixx** [comment]
The application i use accesses the protocol instance from a separate thread for sending commands to MPD. This is why i added the lock.

Of course it would be more clean to delegate sending commands to the main thread at the calling places.
Need to fix this once i have time to.

In the mean time we should introduce a config flag for turning locking off.

**Comment by relevitt** [comment]
@rnixx, thank you for explanation.
