### ISSUE TITLE
TypeError: mpd_command() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by FaustinM** [Mic92/python-mpd2#98]
MPD Version : Music Player Daemon 0.19.1
Python :  Python 3.4.2
Python-mpd2 : 1.0 (?)
I don't understand an error "The error is Traceback (most recent call last):
  File "youtubeMPD.py", line 25, in <module>
    MPDClient.stop()
TypeError: mpd_command() missing 1 required positional argument: 'self' "

My code : 
    
    import sys
    import os
    from mpd import MPDClient
    from subprocess import call
    client = MPDClient(use_unicode=True)
    client.connect("localhost", 4000)
    youtube_url = sys.argv[1]
    
    if len(sys.argv) < 2:
    
        print("Précisez un URL !")
        sys.exit(1)
    
    if os.path.isfile("youtube1.mp3") :
        os.remove("youtube1.mp3")

    command = "youtube-dl --extract-audio --audio-format mp3 --output youtube1.%(ext)s " + youtube_url
    #os.system("youtube-dl --extract-audio --audio-format mp3 --output "youtube1" " + youtube_url)
    call(command.split(), shell=False)
    #time.sleep(2)
    if os.path.isfile("youtube1.mp3") :
        MPDClient.stop()
        MPDClient.clear()
        MPDClient.update()
        MPDClient.play("youtube.mp3")

Thx, Faustin

**Comment by Mic92** [comment]
You have used the MPDClient class instead of the client object.
Try:

```
client.stop()
```

instead of

```
MPDClient.stop()
```

**Comment by Mic92** [comment]
if you call the method via class, the `self` parameter is unbound that would usually point to object itself.

**Comment by Kushanah** [comment]
Ok try when my rpi work !

**Comment by FaustinM** [comment]
Sorry, I have forgot this project... I don't need this project anymore because I have a Echo Dot ^^
